services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: iireenees012/ritsi-backend:1.0
    platform: linux/amd64
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: plataforma_formativa_ritsi
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    image: iireenees012/ritsi-frontend:1.0
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # 🔴 SERVICIO DE SCRIPTS
  scripts:
    image: iireenees012/ritsi-backend:1.0
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: plataforma_formativa_ritsi
      PYTHONPATH: /app
    depends_on:
      - mongo
    working_dir: /app
    restart: "no"

volumes:
  mongo_data:
