import { Plus, Trash2 } from 'lucide-react';

const newQuestion = () => ({ question_text: '', question_type: 'multiple_choice', options: ['', ''], correct_answers: [0] });
const newQuiz = () => ({ title: '', passing_percentage: 70, questions: [newQuestion()] });

export default function QuizEditor({ value = [], onChange }) {
  const updateQuiz = (quizIndex, changes) => onChange(value.map((quiz, index) => index === quizIndex ? { ...quiz, ...changes } : quiz));
  const updateQuestion = (quizIndex, questionIndex, changes) => {
    const quiz = value[quizIndex];
    updateQuiz(quizIndex, { questions: quiz.questions.map((question, index) => index === questionIndex ? { ...question, ...changes } : question) });
  };
  return <section className="wide quiz-editor"><div className="section-title"><div><h2>Evaluaciones</h2><p>Las respuestas correctas solo se envían al backend editorial y nunca al alumnado.</p></div><button type="button" className="secondary-button" onClick={() => onChange([...value, newQuiz()])}><Plus size={16} /> Cuestionario</button></div>{value.map((quiz, quizIndex) => <article className="quiz-editor-card" key={quiz.id || quizIndex}><div className="quiz-editor-heading"><input aria-label={`Título del cuestionario ${quizIndex + 1}`} required placeholder="Título del cuestionario" value={quiz.title} onChange={event => updateQuiz(quizIndex, { title: event.target.value })} /><label>Nota mínima (%)<input type="number" min="0" max="100" value={quiz.passing_percentage} onChange={event => updateQuiz(quizIndex, { passing_percentage: Number(event.target.value) })} /></label><button type="button" className="icon-button danger-button" aria-label={`Eliminar cuestionario ${quizIndex + 1}`} onClick={() => onChange(value.filter((_, index) => index !== quizIndex))}><Trash2 size={16} /></button></div>{quiz.questions.map((question, questionIndex) => <fieldset key={question.id || questionIndex}><legend>Pregunta {questionIndex + 1}</legend><label className="wide">Enunciado<input required value={question.question_text} onChange={event => updateQuestion(quizIndex, questionIndex, { question_text: event.target.value })} /></label><label>Tipo<select value={question.question_type} onChange={event => { const type = event.target.value; updateQuestion(quizIndex, questionIndex, { question_type: type, options: type === 'true_false' ? ['Verdadero', 'Falso'] : question.options, correct_answers: [0] }); }}><option value="multiple_choice">Una respuesta</option><option value="multiple_response">Varias respuestas</option><option value="true_false">Verdadero/Falso</option></select></label>{question.question_type !== 'true_false' && <label className="wide">Opciones, una por línea<textarea required rows="4" value={question.options.join('\n')} onChange={event => updateQuestion(quizIndex, questionIndex, { options: event.target.value.split('\n') })} /></label>}<label>Respuestas correctas (números desde 1)<input required pattern="[0-9, ]+" value={question.correct_answers.map(index => index + 1).join(', ')} onChange={event => updateQuestion(quizIndex, questionIndex, { correct_answers: event.target.value.split(',').map(item => Number(item.trim()) - 1).filter(index => Number.isInteger(index) && index >= 0) })} /></label><button type="button" className="text-button" onClick={() => updateQuiz(quizIndex, { questions: quiz.questions.filter((_, index) => index !== questionIndex) })}>Eliminar pregunta</button></fieldset>)}<button type="button" className="secondary-button" onClick={() => updateQuiz(quizIndex, { questions: [...quiz.questions, newQuestion()] })}><Plus size={16} /> Pregunta</button></article>)}</section>;
}
